# Generated by Django 3.2.6 on 2022-08-19 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mun_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='info',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='Mun_app/media'),
        ),
        migrations.AddField(
            model_name='info',
            name='title',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
