# Generated by Django 3.2.6 on 2022-08-20 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mun_app', '0002_auto_20220820_0013'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, null=True)),
                ('body', models.CharField(max_length=200)),
                ('media', models.ImageField(blank=True, null=True, upload_to='media')),
                ('dte', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=150, null=True)),
                ('experience', models.CharField(max_length=200)),
                ('picture', models.ImageField(blank=True, null=True, upload_to='media')),
            ],
        ),
        migrations.DeleteModel(
            name='Info',
        ),
    ]
