# Generated by Django 3.2.6 on 2022-08-20 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mun_app', '0004_alter_blog_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experience',
            name='experience',
            field=models.TextField(),
        ),
    ]
