# Generated by Django 3.2.6 on 2022-08-21 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mun_app', '0006_blogrelated'),
    ]

    operations = [
        migrations.CreateModel(
            name='textManagementSystem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PageAssociated', models.CharField(max_length=200, null=True)),
                ('Body', models.TextField()),
                ('media', models.ImageField(blank=True, null=True, upload_to='media')),
            ],
        ),
    ]
