# Generated by Django 3.2.6 on 2022-08-21 10:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Mun_app', '0007_textmanagementsystem'),
    ]

    operations = [
        migrations.CreateModel(
            name='Web_Pages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page', models.CharField(default='def', max_length=200)),
            ],
        ),
        migrations.AlterField(
            model_name='textmanagementsystem',
            name='PageAssociated',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='Mun_app.web_pages'),
            preserve_default=False,
        ),
    ]
