# Generated by Django 3.2.6 on 2022-08-22 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mun_app', '0009_alter_textmanagementsystem_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='textmanagementsystem',
            name='Purpose',
            field=models.CharField(default='def', max_length=200),
        ),
    ]
