# Generated by Django 3.2.6 on 2022-08-22 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mun_app', '0010_textmanagementsystem_purpose'),
    ]

    operations = [
        migrations.CreateModel(
            name='TvSeries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SeriesName', models.CharField(default='The office', max_length=200)),
                ('VentSpace', models.TextField(null=True)),
                ('media', models.ImageField(blank=True, null=True, upload_to='media')),
                ('Notes', models.CharField(default='Nothing', max_length=200)),
            ],
        ),
    ]
