# Generated by Django 3.2.6 on 2022-08-22 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mun_app', '0011_tvseries'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tvseries',
            name='VentSpace',
            field=models.TextField(),
        ),
    ]
