# Generated by Django 3.2.6 on 2022-08-23 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mun_app', '0014_auto_20220823_1226'),
    ]

    operations = [
        migrations.AddField(
            model_name='explore',
            name='Message',
            field=models.CharField(default='Dah', max_length=255),
            preserve_default=False,
        ),
    ]
